--- 
format: 1
handler: 
  commit: b6ab399dc76d351bfa24a8c110744aa94a01bd6f
  branch: master
lock: false
repository_url: git@github.com:topfunky/PeepOpen-EditorSupport.git
repository_class: Piston::Git::Repository
